name: effects-haskell
version: 0.1.0.0
license: BSD-2-Clause

language: Haskell2010

dependencies:
  - base >= 4.18 && < 4.20

library:
  source-dirs: src
  exposed-modules:
    - StateFree

executables:
  state-example:
    main: Main.hs
    source-dirs: app
    dependencies:
      - effects-haskell

tests:
  state-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - effects-haskell
      - hspec >= 2.11 && < 2.12
      - QuickCheck >= 2.14 && < 2.16
